# The knn-model's config using by web page
# Arch now only support vanilla_knn_mt_visual@xxxxxx
# xxxxx is decide by your base model's arch
DE-EN[it]:
  data_path: /data1/zhaoqf/0101/fairseq/data-bin/it
  model_path: /data1/zhaoqf/0101/fairseq/pretrain-models/wmt19.de-en/wmt19.de-en.ffn8192.pt
  arch: vanilla_knn_mt_visual@transformer_wmt19_de_en
  knn_mode: inference
  knn_datastore_path: /data1/zhaoqf/0101/fairseq/datastore/vanilla-visual/it
  user_dir: /data1/zhaoqf/0101/fairseq/knnbox/models
  bpe_codes: /data1/zhaoqf/0101/fairseq/pretrain-models/wmt19.de-en/ende30k.fastbpe.code
  beam: "4"
  lenpen: "0.6"
  max_len_a: "1.2"
  source_lang: de
  target_lang: en
  max_tokens: "1024"
  scoring: sacrebleu
  tokenizer: moses

ZH-EN[laws]:
  data_path: /data1/zhaoqf/0101/fairseq/data-bin/zh-en-laws
  model_path: /data1/zhaoqf/0101/fairseq/pretrain-models/zh-en/pretrained.pt
  arch: vanilla_knn_mt_visual@transformer_wmt_en_de
  knn_mode: inference
  knn_datastore_path: /data1/zhaoqf/0101/fairseq/datastore/vanilla-visual/zh-en-laws
  user_dir: /data1/zhaoqf/0101/fairseq/knnbox/models
  bpe_codes: /data1/zhaoqf/0101/fairseq/pretrain-models/zh-en/codes.zh
  beam: "4"
  lenpen: "0.6"
  max_len_a: "1.2"
  source_lang: zh
  target_lang: en
  max_tokens: "1024"
  scoring: sacrebleu
  tokenizer: moses
